sudo: required
services:
  - docker
branches:
  only:
    - master
before_install:
  - docker build -t selest1n/zabbix:0.1.0 .
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker push -t selest1n/zabbix:0.1.0
script:
  - bundle exec rake test
