sudo: required
services:
  - docker
branches:
  only:
    - develop
    - master
before_install:
  - docker pull selest1n/zabbix:tagname:0.10.0
  - docker run selest1n/zabbix:tagname:0.10.0 bash -c "azure --version;"
script:
  - if [ $TRAVIS_BRANCH = "develop" ]; then echo "DEV deploy"; fi
  - if [ $TRAVIS_BRANCH = "master" ]; then docker ps -a; fi
