sudo: required
services:
  - docker
branches:
  only:
    - master
install:
  - docker build -t selest1n/zabbix:0.1.1 .
deploy:
  - provider: script
    script: bash docker_push
    on:
      branch: master
