sudo: required
services:
  - docker
branches:
  only:
    - master
before_install:
  - docker build -t selest1n/zabbix:0.1.0 .
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: master
